# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'CovidView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CovidView
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'FBSDKLoginKit'

  target 'CovidViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CovidViewUITests' do
    # Pods for testing
  end

end
